networks:
  - ssid: !secret iot_ssid # pragma: allowlist secret
    password: !secret phixnet_wifi_iot_pwd # pragma: allowlist secret
    hidden: true
fast_connect: true
domain: !secret domain # pragma: allowlist secret
ap:
  ssid: !secret fallback_ssid # pragma: allowlist secret
  password: !secret fallback_wifi_pwd # pragma: allowlist secret
