#██╗      ██████╗  ██████╗  ██████╗ ██╗███╗   ██╗ ██████╗
#██║     ██╔═══██╗██╔════╝ ██╔════╝ ██║████╗  ██║██╔════╝
#██║     ██║   ██║██║  ███╗██║  ███╗██║██╔██╗ ██║██║  ███╗
#██║     ██║   ██║██║   ██║██║   ██║██║██║╚██╗██║██║   ██║
#███████╗╚██████╔╝╚██████╔╝╚██████╔╝██║██║ ╚████║╚██████╔╝
#╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝
#
logger:
  default: warn
  logs:
    custom_components.google_fit: debug
    custom_components.sensor.places: debug
    homeassistant.components.sensor.deutsche_bahn: debug
    homeassistant.components.google_assistant.http: debug
    homeassistant.components.google_cloud: debug
    homeassistant.components.google: debug
    homeassistant.components.http.ban: warning
    custom_components.sensor.authenticated: debug
    homeassistant.components.icloud: debug
    aiounifi: warn
    homeassistant.components.unifi: warn
    homeassistant.components.device_tracker.unifi: warn
    homeassistant.components.switch.unifi: warn
    homeassistant.components.automation: warn
    aioesphomeapi.connection: warn
recorder:
  purge_keep_days: 30
  db_url: !secret dburl # pragma: allowlist secret
logbook:
system_log:
  fire_event: true
  max_entries: 500
  