#██╗      ██████╗  ██████╗  ██████╗ ██╗███╗   ██╗ ██████╗
#██║     ██╔═══██╗██╔════╝ ██╔════╝ ██║████╗  ██║██╔════╝
#██║     ██║   ██║██║  ███╗██║  ███╗██║██╔██╗ ██║██║  ███╗
#██║     ██║   ██║██║   ██║██║   ██║██║██║╚██╗██║██║   ██║
#███████╗╚██████╔╝╚██████╔╝╚██████╔╝██║██║ ╚████║╚██████╔╝
#╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝
#
logger:
  default: warn
  logs:
    custom_components.google_fit: debug
    homeassistant.components.sensor.deutsche_bahn: debug
    homeassistant.components.google_assistant.http: debug
    homeassistant.components.google_cloud: debug
    homeassistant.components.google: debug
    homeassistant.components.http.ban: warning
    custom_components.sensor.authenticated: debug
    homeassistant.components.icloud: debug
    aiounifi: warn
    homeassistant.components.unifi: warn
    homeassistant.components.device_tracker.unifi: warn
    homeassistant.components.switch.unifi: warn
    homeassistant.components.automation: warn
    aioesphomeapi.connection: warn
recorder:
  purge_keep_days: 30
  db_url: !secret dburl # pragma: allowlist secret
  exclude:
    entities:
      - binary_sensor.outside_temperature_falling
      - binary_sensor.outside_temperature_rising
      - binary_sensor.inside_temperature_falling
      - binary_sensor.inside_temperature_rising
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date
      - sensor.time_date
      - sensor.time_utc
      - sensor.time
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.core
      - sensor.core_2
      - sensor.core_mem
      - sensor.supervisor
      - sensor.supervisor_2
      - sensor.supervisor_mem
      #      - sensor.influxdb_size_telegraf
      #      - sensor.influxdb_size_homeassistant
      #      - sensor.influxdb_size_internal
      #      - sensor.influxdb_size_unifi
      #      - sensor.mariadb_homeassistant
      - sensor.sonoff_pow_r2_whz_power
      - sensor.sonoff_pow_r2_whz_current
      - sensor.sonoff_pow_r2_whz_voltage
      - sensor.sonoff_pow_r2_tv_power
      - sensor.sonoff_pow_r2_tv_current
      - sensor.sonoff_pow_r2_tv_voltage
      - sensor.sonoff_pow_r2_whz_daily_energy
      - sensor.sonoff_pow_r2_tv_daily_energy
      - sensor.energy_combined_power
      - sensor.energy_combined_current
      - sensor.energy_combined_voltage
      - sensor.uptime
      - sensor.dark_sky_alerts
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_humidity
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.hass_uptime
      - sensor.unifi_accesspoint_uptime
      - sensor.unifi_switch_uptime
      - sensor.unifi_usg_uptime
      - sensor.uptime
      - sensor.time
      - sensor.date_time_iso
      - sensor.circadian_values
      - sensor.memory_free
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.reddit_gamedeals
      - sensor.nodemcu_2_wohnzimmer_hohe_nhn
      - sensor.nodemcu_2_wohnzimmer_uptime
      - sensor.schalter_1_bad_uptime
      - sensor.schalter_1_flur_uptime
      - sensor.schalter_1_wohnzimmer_uptime
      - sensor.schalter_lavalampe_uptime
      - sensor.schalter_schrank_kuche_uptime
      - sensor.schalter_schrank_wohnzimmer_uptime
      - sensor.sonoff_pow_r2_tv_uptime
      - sensor.sonoff_pow_r2_whz_uptime
      - sensor.spotlight_1_wohnzimmer_uptime
      - sensor.stehlampe_wohnzimmer_uptime
      - sensor.network_throughput_in_eth0
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - light
      #      - automation
      - group
      - script
      - switch
      - zone
      - time
logbook:
  exclude:
    entities:
      - binary_sensor.outside_temperature_falling
      - binary_sensor.outside_temperature_rising
      - binary_sensor.inside_temperature_falling
      - binary_sensor.inside_temperature_rising
      - binary_sensor.wohnzimmertur
      - sensor.hp_switch_uptime
      - sensor.nas_uptime
      - sensor.core
      - sensor.supervisor
      - sensor.supervisor_mem
      - automation.update_morning_commute_sensor
      - sensor.date_muellabfuhr
      - sensor.hass_uptime
      - sensor.unifi_accesspoint_uptime
      - sensor.unifi_switch_uptime
      - sensor.unifi_usg_uptime
      - sensor.uptime
      - sensor.time
      - sensor.date_time_iso
      - sensor.circadian_values
      - sensor.memory_free
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date
      - sensor.time_date
      - sensor.time_utc
      - sensor.nodemcu_2_wohnzimmer_uptime
      - sensor.schalter_1_bad_uptime
      - sensor.schalter_1_flur_uptime
      - sensor.schalter_1_wohnzimmer_uptime
      - sensor.schalter_lavalampe_uptime
      - sensor.schalter_schrank_kuche_uptime
      - sensor.schalter_schrank_wohnzimmer_uptime
      - sensor.sonoff_pow_r2_tv_uptime
      - sensor.sonoff_pow_r2_whz_uptime
      - sensor.spotlight_1_wohnzimmer_uptime
      - sensor.stehlampe_wohnzimmer_uptime
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.network_throughput_in_eth0
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
history:
  exclude:
    entities:
      - binary_sensor.outside_temperature_falling
      - binary_sensor.outside_temperature_rising
      - binary_sensor.inside_temperature_falling
      - binary_sensor.inside_temperature_rising
      - sensor.influxdb_size_telegraf
      - sensor.influxdb_size_homeassistant
      - sensor.core
      - sensor.supervisor
      - sensor.supervisor_mem
      - sensor.influxdb_size_internal
      - sensor.influxdb_size_unifi
      - sensor.sonoff_pow_r2_whz_power
      - sensor.sonoff_pow_r2_whz_current
      - sensor.sonoff_pow_r2_whz_voltage
      - sensor.sonoff_pow_r2_tv_power
      - sensor.sonoff_pow_r2_tv_current
      - sensor.sonoff_pow_r2_tv_voltage
      - sensor.energy_combined_power
      - sensor.energy_combined_current
      - sensor.energy_combined_voltage
      - sensor.sonoff_th16_whz_temperatur_sensor
      - sensor.sonoff_th16_whz_luftfeuchtigkeit_sensor
      - sensor.climate_flur_temp
      - sensor.climate_bad_temp
      - sensor.climate_wonzimmer_temp
      - sensor.sonoff_pow_r2_whz_daily_energy
      - sensor.sonoff_pow_r2_tv_daily_energy
      - sensor.hass_uptime
      - sensor.unifi_accesspoint_uptime
      - sensor.unifi_switch_uptime
      - sensor.unifi_usg_uptime
      - sensor.hp_switch_uptime
      - sensor.nas_uptime
      - sensor.uptime
      - sensor.time
      - sensor.date_time_iso
      - sensor.date_muellabfuhr
      - sensor.circadian_values
      - sensor.memory_free
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.reddit_gamedeals
      - sensor.rss_coindesk
      - sensor.rss_darknet
      - sensor.rss_free_steam_keys
      - sensor.hass_uptime
      - sensor.hp_switch_uptime
      - sensor.internet_uptime
      - sensor.lampe_bad_uptime
      - sensor.lampe_flur_uptime
      - sensor.lampe_kuche_uptime
      - sensor.led_strip_1_wohnzimmer_uptime
      - sensor.led_strip_2_wohnzimmer_uptime
      - sensor.nas_uptime
      - sensor.nodemcu_2_wohnzimmer_uptime
      - sensor.schalter_1_bad_uptime
      - sensor.schalter_1_flur_uptime
      - sensor.schalter_1_wohnzimmer_uptime
      - sensor.schalter_lavalampe_uptime
      - sensor.schalter_schrank_kuche_uptime
      - sensor.schalter_schrank_wohnzimmer_uptime
      - sensor.sonoff_pow_r2_tv_uptime
      - sensor.sonoff_pow_r2_whz_uptime
      - sensor.spotlight_1_wohnzimmer_uptime
      - sensor.stehlampe_wohnzimmer_uptime
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.network_throughput_in_eth0
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
#      - device_tracker
system_log:
  fire_event: true
  max_entries: 500

#recorder:
#  purge_keep_days: 30
#  db_url: !secret dburl # pragma: allowlist secret
#  include:
#    domains:
#      - alarm_control_panel
#      - light
#      - device_tracker
#      - switch
#      - media_player
#      - sensor
#  exclude:
#    event_types:
#      - call_service
#    domains:
#      - time
#    entities:
#      - binary_sensor.outside_temperature_falling
#      - binary_sensor.outside_temperature_rising
#      - binary_sensor.inside_temperature_falling
#      - binary_sensor.inside_temperature_rising
#      - sensor.influxdb_size_telegraf
#      - sensor.influxdb_size_homeassistant
#      - sensor.core
#      - sensor.supervisor
#      - sensor.supervisor_mem
#      - sensor.influxdb_size_internal
#      - sensor.influxdb_size_unifi
#      - sensor.sonoff_pow_r2_whz_power
#      - sensor.sonoff_pow_r2_whz_current
#      - sensor.sonoff_pow_r2_whz_voltage
#      - sensor.sonoff_pow_r2_tv_power
#      - sensor.sonoff_pow_r2_tv_current
#      - sensor.sonoff_pow_r2_tv_voltage
#      - sensor.energy_combined_power
#      - sensor.energy_combined_current
#      - sensor.energy_combined_voltage
#      - sensor.sonoff_th16_whz_temperatur_sensor
#      - sensor.sonoff_th16_whz_luftfeuchtigkeit_sensor
#      - sensor.climate_flur_temp
#      - sensor.climate_bad_temp
#      - sensor.climate_wonzimmer_temp
#      - sensor.sonoff_pow_r2_whz_daily_energy
#      - sensor.sonoff_pow_r2_tv_daily_energy
#      - sensor.hass_uptime
#      - sensor.unifi_accesspoint_uptime
#      - sensor.unifi_switch_uptime
#      - sensor.unifi_usg_uptime
#      - sensor.hp_switch_uptime
#      - sensor.nas_uptime
#      - sensor.uptime
#      - sensor.date_time
#      - sensor.date_time_iso
#      - sensor.date
#      - sensor.time_date
#      - sensor.time_utc
#      - sensor.date_muellabfuhr
#      - sensor.circadian_values
#      - sensor.memory_free
#      - sensor.network_in_eth0
#      - sensor.network_out_eth0
#      - sensor.reddit_gamedeals
#      - sensor.rss_coindesk
#      - sensor.rss_darknet
#      - sensor.rss_free_steam_keys
#      - sensor.hass_uptime
#      - sensor.hp_switch_uptime
#      - sensor.internet_uptime
#      - sensor.lampe_bad_uptime
#      - sensor.lampe_flur_uptime
#      - sensor.lampe_kuche_uptime
#      - sensor.led_strip_1_wohnzimmer_uptime
#      - sensor.led_strip_2_wohnzimmer_uptime
#      - sensor.nas_uptime
#      - sensor.nodemcu_2_wohnzimmer_uptime
#      - sensor.schalter_1_bad_uptime
#      - sensor.schalter_1_flur_uptime
#      - sensor.schalter_1_wohnzimmer_uptime
#      - sensor.schalter_lavalampe_uptime
#      - sensor.schalter_schrank_kuche_uptime
#      - sensor.schalter_schrank_wohnzimmer_uptime
#      - sensor.sonoff_pow_r2_tv_uptime
#      - sensor.sonoff_pow_r2_whz_uptime
#      - sensor.spotlight_1_wohnzimmer_uptime
#      - sensor.stehlampe_wohnzimmer_uptime
#      - sensor.load_1m
#      - sensor.load_5m
#      - sensor.load_15m
#      - sensor.network_throughput_in_eth0
#history:
#  include:
#    domains:
#      - alarm_control_panel
#      - light
#      - device_tracker
#      - switch
#      - media_player
#      - sensor
#  exclude:
#    domains:
#      - time
#    entities:
#      - binary_sensor.outside_temperature_falling
#      - binary_sensor.outside_temperature_rising
#      - binary_sensor.inside_temperature_falling
#      - binary_sensor.inside_temperature_rising
#      - sensor.influxdb_size_telegraf
#      - sensor.influxdb_size_homeassistant
#      - sensor.core
#      - sensor.supervisor
#      - sensor.supervisor_mem
#      - sensor.influxdb_size_internal
#      - sensor.influxdb_size_unifi
#      - sensor.sonoff_pow_r2_whz_power
#      - sensor.sonoff_pow_r2_whz_current
#      - sensor.sonoff_pow_r2_whz_voltage
#      - sensor.sonoff_pow_r2_tv_power
#      - sensor.sonoff_pow_r2_tv_current
#      - sensor.sonoff_pow_r2_tv_voltage
#      - sensor.energy_combined_power
#      - sensor.energy_combined_current
#      - sensor.energy_combined_voltage
#      - sensor.sonoff_th16_whz_temperatur_sensor
#      - sensor.sonoff_th16_whz_luftfeuchtigkeit_sensor
#      - sensor.climate_flur_temp
#      - sensor.climate_bad_temp
#      - sensor.climate_wonzimmer_temp
#      - sensor.sonoff_pow_r2_whz_daily_energy
#      - sensor.sonoff_pow_r2_tv_daily_energy
#      - sensor.hass_uptime
#      - sensor.unifi_accesspoint_uptime
#      - sensor.unifi_switch_uptime
#      - sensor.unifi_usg_uptime
#      - sensor.hp_switch_uptime
#      - sensor.nas_uptime
#      - sensor.uptime
#      - sensor.time
#      - sensor.date_time_iso
#      - sensor.date_muellabfuhr
#      - sensor.circadian_values
#      - sensor.memory_free
#      - sensor.network_in_eth0
#      - sensor.network_out_eth0
#      - sensor.reddit_gamedeals
#      - sensor.rss_coindesk
#      - sensor.rss_darknet
#      - sensor.rss_free_steam_keys
#      - sensor.hass_uptime
#      - sensor.hp_switch_uptime
#      - sensor.internet_uptime
#      - sensor.lampe_bad_uptime
#      - sensor.lampe_flur_uptime
#      - sensor.lampe_kuche_uptime
#      - sensor.led_strip_1_wohnzimmer_uptime
#      - sensor.led_strip_2_wohnzimmer_uptime
#      - sensor.nas_uptime
#      - sensor.nodemcu_2_wohnzimmer_uptime
#      - sensor.schalter_1_bad_uptime
#      - sensor.schalter_1_flur_uptime
#      - sensor.schalter_1_wohnzimmer_uptime
#      - sensor.schalter_lavalampe_uptime
#      - sensor.schalter_schrank_kuche_uptime
#      - sensor.schalter_schrank_wohnzimmer_uptime
#      - sensor.sonoff_pow_r2_tv_uptime
#      - sensor.sonoff_pow_r2_whz_uptime
#      - sensor.spotlight_1_wohnzimmer_uptime
#      - sensor.stehlampe_wohnzimmer_uptime
#      - sensor.load_1m
#      - sensor.load_5m
#      - sensor.load_15m
#      - sensor.network_throughput_in_eth0
#
#logbook:
#  include:
#    domains:
#      - alarm_control_panel
#      - light
#      - device_tracker
#      - switch
#      - media_player
#      - sensor
#  exclude:
#    domains:
#      - time
#    entities:
#      - binary_sensor.outside_temperature_falling
#      - binary_sensor.outside_temperature_rising
#      - binary_sensor.inside_temperature_falling
#      - binary_sensor.inside_temperature_rising
#      - sensor.influxdb_size_telegraf
#      - sensor.influxdb_size_homeassistant
#      - sensor.core
#      - sensor.supervisor
#      - sensor.supervisor_mem
#      - sensor.influxdb_size_internal
#      - sensor.influxdb_size_unifi
#      - sensor.sonoff_pow_r2_whz_power
#      - sensor.sonoff_pow_r2_whz_current
#      - sensor.sonoff_pow_r2_whz_voltage
#      - sensor.sonoff_pow_r2_tv_power
#      - sensor.sonoff_pow_r2_tv_current
#      - sensor.sonoff_pow_r2_tv_voltage
#      - sensor.energy_combined_power
#      - sensor.energy_combined_current
#      - sensor.energy_combined_voltage
#      - sensor.sonoff_th16_whz_temperatur_sensor
#      - sensor.sonoff_th16_whz_luftfeuchtigkeit_sensor
#      - sensor.climate_flur_temp
#      - sensor.climate_bad_temp
#      - sensor.climate_wonzimmer_temp
#      - sensor.sonoff_pow_r2_whz_daily_energy
#      - sensor.sonoff_pow_r2_tv_daily_energy
#      - sensor.hass_uptime
#      - sensor.unifi_accesspoint_uptime
#      - sensor.unifi_switch_uptime
#      - sensor.unifi_usg_uptime
#      - sensor.hp_switch_uptime
#      - sensor.nas_uptime
#      - sensor.uptime
#      - sensor.date_time
#      - sensor.date_time_iso
#      - sensor.date
#      - sensor.time
#      - sensor.time_date
#      - sensor.time_utc
#      - sensor.date_muellabfuhr
#      - sensor.circadian_values
#      - sensor.memory_free
#      - sensor.network_in_eth0
#      - sensor.network_out_eth0
#      - sensor.reddit_gamedeals
#      - sensor.rss_coindesk
#      - sensor.rss_darknet
#      - sensor.rss_free_steam_keys
#      - sensor.hass_uptime
#      - sensor.hp_switch_uptime
#      - sensor.internet_uptime
#      - sensor.lampe_bad_uptime
#      - sensor.lampe_flur_uptime
#      - sensor.lampe_kuche_uptime
#      - sensor.led_strip_1_wohnzimmer_uptime
#      - sensor.led_strip_2_wohnzimmer_uptime
#      - sensor.nas_uptime
#      - sensor.nodemcu_2_wohnzimmer_uptime
#      - sensor.schalter_1_bad_uptime
#      - sensor.schalter_1_flur_uptime
#      - sensor.schalter_1_wohnzimmer_uptime
#      - sensor.schalter_lavalampe_uptime
#      - sensor.schalter_schrank_kuche_uptime
#      - sensor.schalter_schrank_wohnzimmer_uptime
#      - sensor.sonoff_pow_r2_tv_uptime
#      - sensor.sonoff_pow_r2_whz_uptime
#      - sensor.spotlight_1_wohnzimmer_uptime
#      - sensor.stehlampe_wohnzimmer_uptime
#      - sensor.load_1m
#      - sensor.load_5m
#      - sensor.load_15m
#      - sensor.network_throughput_in_eth0
#system_log:
#  fire_event: true
#  max_entries: 500
