- alias: "Telegram Play froggy on TV"
  id: "38a"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: "/yt_froggy"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Status"
    - service: homeassistant.toggle
      entity_id: input_boolean.play_froggy
- alias: Notification froggy Video
  id: "11a"
  trigger:
    - platform: state
      entity_id: sensor.froggy18157725
      attribute: url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_froggy_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_froggy_video.attributes.last_triggered != none }}"
  action:
    - service: notify.telegram
      data_template:
        title: New froggy Video
        message: >
          {{states('sensor.froggy18157725')}}
           {{state_attr('sensor.froggy18157725', 'url')}}
        data:
          inline_keyboard:
            - "Play Video on TV:/yt_froggy"
    - service: rest_command.assistant_broadcast
      data_template:
        command: Hey Martin, froggy hat ein neues Video auf YouTube hochgeladen.
    - service: notify.lametric
      data:
        message: "Neues froggy Video {{states.sensor.froggy18157725.state}}"
        data:
          sound: "notification"
          icon: "a10835"
          cycles: 0
          lifetime: 3600
          priority: "critical"
- alias: AndroidTV Play Latest froggy Video
  id: "28a"
  trigger:
    platform: state
    entity_id: input_boolean.play_froggy
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.shield
      data_template:
        media_content_id: "{{state_attr('sensor.froggy18157725', 'url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_froggy

