- alias: "Telegram Play nexpo on TV"
  id: "38"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: "/yt_nexpo"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Status"
    - service: homeassistant.toggle
      entity_id: input_boolean.play_nexpo
- alias: Notification Nexpo Video
  id: "11"
  trigger:
    - platform: state
      entity_id: sensor.nexpo
      attribute: url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_nexpo_video.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_nexpo_video.attributes.last_triggered != none }}"
  action:
    - service: notify.telegram
      data_template:
        title: New Nexpo Video
        message: >
          {{states('sensor.nexpo')}}
           {{state_attr('sensor.nexpo', 'url')}}
        data:
          inline_keyboard:
            - "Play Video on TV:/yt_nexpo"
    - service: rest_command.assistant_broadcast
      data_template:
        command: Hey Martin, Nexpo hat ein neues Video auf YouTube hochgeladen.
    - service: notify.lametric
      data:
        message: "Neues Nexpo Video"
        data:
          sound: 'notification'
          icon: 'a10835'
          cycles: 10
          priority: 'critical'
- alias: AndroidTV Play Latest Nexpo Video
  id: "28"
  trigger:
    platform: state
    entity_id: input_boolean.play_nexpo
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.shield
      data_template:
        media_content_id: "{{state_attr('sensor.nexpo', 'url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_nexpo

