- alias: "Telegram Play JB3 on TV"
  id: "37"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      command: "/yt_jb3"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Status"
    - service: homeassistant.toggle
      entity_id: input_boolean.play_jb3
- alias: AndroidTV Play Latest JB3 Video
  id: "30"
  trigger:
    platform: state
    entity_id: input_boolean.play_jb3
    to: "on"
  action:
    - service: media_extractor.play_media
      entity_id:
        - media_player.shield
      data_template:
        media_content_id: "{{state_attr('sensor.jb3', 'url' | string)}}"
        media_content_type: video/youtube
    - service: homeassistant.turn_off
      entity_id: input_boolean.play_jb3
- alias: Notification JB3 Video
  id: "10"
  trigger:
    - platform: state
      entity_id: sensor.jb3
      attribute: url
  condition:
    - condition: template
      value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.notification_jb3.attributes.last_triggered) | int > 900 }}"
    - condition: template
      value_template: "{{ states.automation.notification_jb3.attributes.last_triggered != none }}"
  action:
    - service: notify.telegram
      data_template:
        title: New JB3 Video
        message: >
          {{states('sensor.jb3')}}
           {{state_attr('sensor.jb3', 'url')}}
        data:
          inline_keyboard:
            - "Play Video on TV:/yt_jb3"
    - service: notify.lametric
      data:
        message: "Neues JB3 Video: {{states.sensor.jb3.state}}"
        data:
          sound: 'notification'
          icon: 'a10835'
          cycles: 10
          priority: 'critical'