substitutions:
  devicename: nodemcu8
  friendly_name: Nodemcu 8
  room: Wohnzimmer
  update_interval_short: 2min
  update_interval_long: 10min
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
text_sensor: !include shared/textsensors.yaml
web_server: !include shared/webserver.yaml
captive_portal:
logger:
sensor:
  - platform: wifi_signal
    name: ${friendly_name} (${room}) WiFi Signal
    update_interval: ${update_interval_long}
    unit_of_measurement: dB
    icon: mdi:wifi
  - platform: uptime
    force_update: true
    id: ${devicename}_uptime
    internal: true
    update_interval: ${update_interval_long}
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
